services:
  - docker:dind

variables:
  GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
  GIT_STRATEGY: clone
  IMAGE_NAME: dlgim/$CI_PROJECT_NAME
  BUILD_NUMBER: '${CI_PIPELINE_IID}'
  PROD_URL: 'https://dlg.im'
  DEV_URL: 'https://demo.dlg.im'

cache:
  key: '${CI_COMMIT_SHA}'
  paths:
    - ./node_modules
    - ./server
    - ./public

stages:
  - version
  - build
  - docker
  - deploy
  - notify

version:
  image: gitlab.transmit.im:5001/gitlab/builders/web-builder:latest
  stage: version
  script:
    - |
      curl --header 'Content-Type: application/json' --request POST \
      --data "{\"text\": \"👉🏾 Homepage build *#${BUILD_NUMBER}*: pipeline started.\"}" \
      $DIALOG_WEBHOOK

    - version=$(node -p "require('./package.json').version")
    - image_version="$version.${BUILD_NUMBER}"
    - echo $image_version
    - echo "export IMAGE_VERSION=$image_version" > variables
  artifacts:
    paths:
      - variables

build:
  image: gitlab.transmit.im:5001/gitlab/builders/web-builder:latest
  stage: build
  script:
    - source variables
    - npm ci
    - npm run build

    - |
      curl --header 'Content-Type: application/json' --request POST \
      --data "{\"text\": \"👌🏾 Homepage build *#${BUILD_NUMBER}*: application build successful.\"}" \
      $DIALOG_WEBHOOK
  dependencies:
    - version

docker build:
  stage: docker
  script:
    - source variables
    - docker login -u="${REGISTRY_USER}" -p="${REGISTRY_PASSWORD}" "${REGISTRY}"
    - docker build -t "${REGISTRY}"/"${IMAGE_NAME}":"${IMAGE_VERSION}" .
    - docker tag "${REGISTRY}"/"${IMAGE_NAME}":"${IMAGE_VERSION}" "${REGISTRY}"/"${IMAGE_NAME}":latest
    - docker push "${REGISTRY}"/"${IMAGE_NAME}":"${IMAGE_VERSION}"
    - if [ "${CI_COMMIT_REF_NAME}" = "master" ]; then docker push "${REGISTRY}"/"${IMAGE_NAME}":latest; fi

    - |
      curl --header 'Content-Type: application/json' --request POST \
      --data "{\"text\": \"👌🏾 Homepage build *#${BUILD_NUMBER}:* docker image ready. ${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}\"}" \
      $DIALOG_WEBHOOK
  dependencies:
    - version
    - build

staging:
  stage: deploy
  environment:
    name: staging
    url: '${DEV_URL}'
    EMAIL_TO: 'oleg@dlg.im'
  cache: {}
  image: gitlab.transmit.im:5001/gitlab/builders/ansible
  script:
    - source variables
    - |
      curl --header 'Content-Type: application/json' --request POST \
      --data "{\"text\": \"👉🏾 Homepage build *#${BUILD_NUMBER}:* deploy to DEV started.\"}" \
      $DIALOG_WEBHOOK
    - eval `ssh-agent`
    - echo "$SSH_CI_KEY" | base64 -d | ssh-add -

    - git clone git@gitlab.transmit.im:web/ansible-playbooks/homepage.git
    - cd homepage && ansible-galaxy install -r requirements.yml
    - ansible-playbook -u root playbook.yml --diff -e homepage_http_port=7083 -e homepage_service_name="homepage-demo" -e homepage_container="${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}" --limit homepage-old
    - |
      curl --header 'Content-Type: application/json' --request POST \
      --data "{\"text\": \"🤟🏾 Homepage build *#${BUILD_NUMBER}:* DEV successfully deployed. [Check here](${DEV_URL})\"}" \
      $DIALOG_WEBHOOK
  dependencies:
    - version
  only:
    - develop
  tags:
    - sbc-deploy

prod:
  stage: deploy
  environment:
    name: prod
    url: '${PROD_URL}'
  cache: {}
  image: gitlab.transmit.im:5001/gitlab/builders/ansible
  script:
    - source variables
    - |
      curl --header 'Content-Type: application/json' --request POST \
      --data "{\"text\": \"👉🏾 Homepage build *#${BUILD_NUMBER}:* deploy to PROD started.\"}" \
      $DIALOG_WEBHOOK

    - eval `ssh-agent`
    - echo "$SSH_CI_KEY" | base64 -d | ssh-add -
    - git clone git@gitlab.transmit.im:web/ansible-playbooks/homepage.git
    - cd homepage && ansible-galaxy install -r requirements.yml
    - ansible-playbook -u root playbook.yml --diff -e homepage_http_port=8083 -e homepage_service_name="${CI_PROJECT_NAME}" -e homepage_container="${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}" --limit homepage-old

    - |
      curl --header 'Content-Type: application/json' --request POST \
      --data "{\"text\": \"🤟🏾 Homepage build *#${BUILD_NUMBER}:* PROD successfully deployed. [Check here](${PROD_URL})\"}" \
      $DIALOG_WEBHOOK
  dependencies:
    - version
  only:
    - master
  tags:
    - sbc-deploy

notify_fail:
  stage: notify
  when: on_failure
  script:
    - |
      curl --header 'Content-Type: application/json' --request POST \
      --data "{\"text\": \"🖕🏾 Homepage build *#${BUILD_NUMBER}:* pipeline failed. [More info](${CI_PIPELINE_URL})\"}" \
      $DIALOG_WEBHOOK
